# Generated by Django 4.1.2 on 2022-10-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
