# Generated by Django 4.1.2 on 2022-10-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_qrcode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='title',
            field=models.CharField(blank=True, default='Link', max_length=100, null=True),
        ),
    ]
